// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Paybitch.Infrastructure;

#nullable disable

namespace Paybitch.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ActivityLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUser")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verb");

                    b.HasKey("Id")
                        .HasName("pk_activity_log");

                    b.HasIndex("ActorUser")
                        .HasDatabaseName("ix_activity_log_actor_user");

                    b.HasIndex("GroupId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_activity_group_time");

                    b.ToTable("activity_log", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.AuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("AppleRefreshTokenEnc")
                        .HasColumnType("bytea")
                        .HasColumnName("apple_refresh_token_enc");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_identities_user_id");

                    b.HasIndex("Provider", "Subject")
                        .IsUnique()
                        .HasDatabaseName("uq_auth_identities_provider_subject");

                    b.ToTable("auth_identities", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.BlobDeletion", b =>
                {
                    b.Property<Guid>("StorageKey")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_key");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("StorageKey")
                        .HasName("pk_blob_deletions");

                    b.HasIndex("RequestedAt")
                        .HasDatabaseName("ix_blob_deletions_pending")
                        .HasFilter("confirmed_at IS NULL");

                    b.ToTable("blob_deletions", null, t =>
                        {
                            t.HasCheckConstraint("ck_blob_deletions_reason", "reason IN ('attachment_purged','avatar_replaced','gdpr_erase','orphan')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("IconSymbol")
                        .HasColumnType("text")
                        .HasColumnName("icon_symbol");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_categories_global")
                        .HasFilter("group_id IS NULL AND deleted_at IS NULL");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_categories_group")
                        .HasFilter("group_id IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "cart.fill",
                            Name = "groceries",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "fork.knife",
                            Name = "dining",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "car.fill",
                            Name = "transport",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "house.fill",
                            Name = "housing",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "bolt.fill",
                            Name = "utilities",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "popcorn.fill",
                            Name = "entertainment",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "airplane",
                            Name = "travel",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "cross.case.fill",
                            Name = "health",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "bag.fill",
                            Name = "shopping",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("11110000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IconSymbol = "ellipsis.circle.fill",
                            Name = "other",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ChangeLogEntry", b =>
                {
                    b.Property<long>("Seq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Seq"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_delete");

                    b.HasKey("Seq")
                        .HasName("pk_change_log");

                    b.HasIndex("EntityId", "Seq")
                        .HasDatabaseName("ix_change_log_access")
                        .HasFilter("entity_type = 'access'");

                    b.HasIndex("GroupId", "Seq")
                        .HasDatabaseName("ix_change_log_group");

                    b.ToTable("change_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_log_entity_type", "entity_type IN ('group','member','expense','settlement','category','access','recurring_rule','comment')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ChangeLogWatermark", b =>
                {
                    b.Property<bool>("One")
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("one");

                    b.Property<DateTimeOffset?>("PrunedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pruned_at");

                    b.Property<long>("PrunedThroughSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("pruned_through_seq");

                    b.HasKey("One")
                        .HasName("pk_change_log_watermark");

                    b.ToTable("change_log_watermark", null, t =>
                        {
                            t.HasCheckConstraint("ck_change_log_watermark_one", "one");
                        });

                    b.HasData(
                        new
                        {
                            One = true,
                            PrunedThroughSeq = 0L
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUser")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("AuthorUser")
                        .HasDatabaseName("ix_comments_author");

                    b.HasIndex("GroupId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("uq_comments_group_client");

                    b.HasIndex("ExpenseId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_comments_expense")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("comments", null, t =>
                        {
                            t.HasCheckConstraint("ck_comments_body_length", "length(body) BETWEEN 1 AND 2000");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<short>("MinorUnits")
                        .HasColumnType("smallint")
                        .HasColumnName("minor_units");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("Code")
                        .HasName("pk_currencies");

                    b.ToTable("currencies", null, t =>
                        {
                            t.HasCheckConstraint("ck_currencies_minor_units", "minor_units BETWEEN 0 AND 4");
                        });

                    b.HasData(
                        new
                        {
                            Code = "CZK",
                            MinorUnits = (short)0,
                            Symbol = "Kč"
                        },
                        new
                        {
                            Code = "EUR",
                            MinorUnits = (short)2,
                            Symbol = "€"
                        },
                        new
                        {
                            Code = "USD",
                            MinorUnits = (short)2,
                            Symbol = "$"
                        },
                        new
                        {
                            Code = "GBP",
                            MinorUnits = (short)2,
                            Symbol = "£"
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApnsToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apns_token");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("apns")
                        .HasColumnName("kind");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ios")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("UserId", "ApnsToken")
                        .IsUnique()
                        .HasDatabaseName("uq_devices_user_apns_token");

                    b.ToTable("devices", null, t =>
                        {
                            t.HasCheckConstraint("ck_devices_kind", "kind IN ('apns','apns_live_activity')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.EmailLoginToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("code_hash");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<IPAddress>("CreatedIp")
                        .HasColumnType("inet")
                        .HasColumnName("created_ip");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_login_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_email_tokens_expiry");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_email_login_tokens_user_id");

                    b.HasIndex("Email", "Purpose", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_email_tokens_lookup")
                        .HasFilter("consumed_at IS NULL");

                    b.ToTable("email_login_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_login_tokens_purpose", "purpose IN ('login','link','verify_change')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.EmailSuppression", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Email")
                        .HasName("pk_email_suppressions");

                    b.ToTable("email_suppressions", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_suppressions_reason", "reason IN ('bounce','complaint','manual')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("IconSymbol")
                        .HasColumnType("text")
                        .HasColumnName("icon_symbol");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by");

                    b.Property<Guid?>("RecurringRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_rule_id");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("split_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_expenses_category_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_expenses_created_by");

                    b.HasIndex("Currency")
                        .HasDatabaseName("ix_expenses_currency");

                    b.HasIndex("PaidBy")
                        .HasDatabaseName("ix_expenses_paid_by");

                    b.HasIndex("RecurringRuleId")
                        .HasDatabaseName("ix_expenses_recurring")
                        .HasFilter("recurring_rule_id IS NOT NULL");

                    b.HasIndex("GroupId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("uq_expenses_group_client");

                    b.HasIndex("GroupId", "ExpenseDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_expenses_group_date")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_expenses_date_min", "expense_date >= DATE '2000-01-01'");

                            t.HasCheckConstraint("ck_expenses_notes_length", "notes IS NULL OR length(notes) <= 2000");

                            t.HasCheckConstraint("ck_expenses_split_type", "split_type IN ('equal','exact','shares','percentage')");

                            t.HasCheckConstraint("ck_expenses_title_length", "length(title) BETWEEN 1 AND 140");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ExpenseSplit", b =>
                {
                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("GroupMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_member_id");

                    b.Property<int?>("BasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("basis_points");

                    b.Property<long>("ShareMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("share_minor");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("ExpenseId", "GroupMemberId")
                        .HasName("pk_expense_splits");

                    b.HasIndex("GroupMemberId")
                        .HasDatabaseName("ix_splits_member");

                    b.ToTable("expense_splits", null, t =>
                        {
                            t.HasCheckConstraint("ck_expense_splits_share_non_negative", "share_minor >= 0");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ExportResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<byte[]>("ContentHash")
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Params")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("params")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.HasKey("Id")
                        .HasName("pk_export_results");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_export_results_group_id");

                    b.HasIndex("RequestedBy", "RequestedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_export_results_user");

                    b.ToTable("export_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_export_results_content_type", "content_type IN ('text/csv','application/pdf','application/json')");

                            t.HasCheckConstraint("ck_export_results_kind", "kind IN ('csv','pdf','gdpr')");

                            t.HasCheckConstraint("ck_export_results_status", "status IN ('pending','ready','failed','expired')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("default_currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("IconSymbol")
                        .HasColumnType("text")
                        .HasColumnName("icon_symbol");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_groups_created_by");

                    b.HasIndex("DefaultCurrency")
                        .HasDatabaseName("ix_groups_default_currency");

                    b.ToTable("groups", null, t =>
                        {
                            t.HasCheckConstraint("ck_groups_name_length", "length(name) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("FormerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("former_user_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("IconSymbol")
                        .HasColumnType("text")
                        .HasColumnName("icon_symbol");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("member")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("FormerUserId")
                        .HasDatabaseName("ix_group_members_former_user_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_members_group")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_group_members_user")
                        .HasFilter("user_id IS NOT NULL AND deleted_at IS NULL");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_group_members_group_user");

                    b.ToTable("group_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_members_ghost_role", "user_id IS NOT NULL OR role = 'member'");

                            t.HasCheckConstraint("ck_group_members_role", "role IN ('owner','admin','member')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_invites_group_id");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_invites_invited_by");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_invites_member_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_invites_token_hash");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupeKey")
                        .HasColumnType("text")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(8)
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)100)
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("RunAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("queued")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("uq_jobs_dedupe")
                        .HasFilter("dedupe_key IS NOT NULL AND status IN ('queued','running')");

                    b.HasIndex("LockedAt")
                        .HasDatabaseName("ix_jobs_reap")
                        .HasFilter("status = 'running'");

                    b.HasIndex("Priority", "RunAt")
                        .HasDatabaseName("ix_jobs_claim")
                        .HasFilter("status = 'queued'");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_status", "status IN ('queued','running','succeeded','failed','dead')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.NotificationCursor", b =>
                {
                    b.Property<string>("Worker")
                        .HasColumnType("text")
                        .HasColumnName("worker");

                    b.Property<Guid>("LastActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_activity_id");

                    b.Property<DateTimeOffset>("LastCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Worker")
                        .HasName("pk_notification_cursor");

                    b.ToTable("notification_cursor", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.NotificationPref", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notification_prefs");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_notification_prefs_group_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notif_prefs_user");

                    b.HasIndex("UserId", "EventType", "Channel")
                        .IsUnique()
                        .HasDatabaseName("uq_notif_prefs_global")
                        .HasFilter("group_id IS NULL");

                    b.HasIndex("UserId", "GroupId", "EventType", "Channel")
                        .IsUnique()
                        .HasDatabaseName("uq_notif_prefs_group")
                        .HasFilter("group_id IS NOT NULL");

                    b.ToTable("notification_prefs", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_prefs_channel", "channel IN ('push','email')");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RateLimitCounter", b =>
                {
                    b.Property<byte[]>("PartitionHash")
                        .HasColumnType("bytea")
                        .HasColumnName("partition_hash");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count");

                    b.HasKey("PartitionHash", "WindowStart")
                        .HasName("pk_rate_limit_counters");

                    b.HasIndex("WindowStart")
                        .HasDatabaseName("ix_rate_limit_gc");

                    b.ToTable("rate_limit_counters", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RecurringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<int?>("ByMonthDay")
                        .HasColumnType("integer")
                        .HasColumnName("by_month_day");

                    b.Property<int?>("ByWeekday")
                        .HasColumnType("integer")
                        .HasColumnName("by_weekday");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date")
                        .HasColumnName("ends_on");

                    b.Property<string>("Freq")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("freq");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("IconSymbol")
                        .HasColumnType("text")
                        .HasColumnName("icon_symbol");

                    b.Property<int>("Interval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("interval");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<DateTimeOffset?>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by");

                    b.Property<string>("PauseReason")
                        .HasColumnType("text")
                        .HasColumnName("pause_reason");

                    b.Property<int?>("RemainingCount")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_count");

                    b.Property<string>("SplitType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("split_type");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date")
                        .HasColumnName("starts_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_recurring_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurring_rules_category_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_recurring_rules_created_by");

                    b.HasIndex("Currency")
                        .HasDatabaseName("ix_recurring_rules_currency");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_recurring_group")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("NextRunAt")
                        .HasDatabaseName("ix_recurring_due")
                        .HasFilter("status = 'active' AND deleted_at IS NULL");

                    b.HasIndex("PaidBy")
                        .HasDatabaseName("ix_recurring_rules_paid_by");

                    b.HasIndex("GroupId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("uq_recurring_rules_group_client");

                    b.ToTable("recurring_rules", null, t =>
                        {
                            t.HasCheckConstraint("ck_recurring_rules_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_recurring_rules_by_month_day", "by_month_day IS NULL OR by_month_day BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_recurring_rules_by_weekday", "by_weekday IS NULL OR by_weekday BETWEEN 1 AND 7");

                            t.HasCheckConstraint("ck_recurring_rules_end_bound_xor", "NOT (ends_on IS NOT NULL AND remaining_count IS NOT NULL)");

                            t.HasCheckConstraint("ck_recurring_rules_ended_next_run", "(status = 'ended') = (next_run_at IS NULL)");

                            t.HasCheckConstraint("ck_recurring_rules_ends_after_starts", "ends_on IS NULL OR ends_on >= starts_on");

                            t.HasCheckConstraint("ck_recurring_rules_freq", "freq IN ('weekly','monthly','yearly')");

                            t.HasCheckConstraint("ck_recurring_rules_interval", "\"interval\" BETWEEN 1 AND 60");

                            t.HasCheckConstraint("ck_recurring_rules_monthly_shape", "freq <> 'monthly' OR (by_month_day IS NOT NULL AND by_weekday IS NULL)");

                            t.HasCheckConstraint("ck_recurring_rules_notes_length", "notes IS NULL OR length(notes) <= 2000");

                            t.HasCheckConstraint("ck_recurring_rules_pause_reason", "pause_reason IN ('user','member_removed','payer_removed','backlog_exceeded','group_archived')");

                            t.HasCheckConstraint("ck_recurring_rules_remaining_count", "remaining_count IS NULL OR remaining_count >= 0");

                            t.HasCheckConstraint("ck_recurring_rules_status", "status IN ('active','paused','ended')");

                            t.HasCheckConstraint("ck_recurring_rules_title_length", "length(title) BETWEEN 1 AND 140");

                            t.HasCheckConstraint("ck_recurring_rules_weekly_shape", "freq <> 'weekly' OR (by_weekday IS NOT NULL AND by_month_day IS NULL)");

                            t.HasCheckConstraint("ck_recurring_rules_yearly_shape", "freq <> 'yearly' OR (by_weekday IS NULL AND by_month_day IS NULL)");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RecurringRuleSplit", b =>
                {
                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("rule_id");

                    b.Property<Guid>("GroupMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_member_id");

                    b.Property<long?>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<int?>("BasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("basis_points");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("RuleId", "GroupMemberId")
                        .HasName("pk_recurring_rule_splits");

                    b.HasIndex("GroupMemberId")
                        .HasDatabaseName("ix_recurring_rule_splits_group_member_id");

                    b.ToTable("recurring_rule_splits", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ReplacedBy")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("uq_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_user")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinor")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor");

                    b.Property<string>("ClientId")
                        .HasColumnType("text")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FromMember")
                        .HasColumnType("uuid")
                        .HasColumnName("from_member");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Method")
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("SettledOn")
                        .HasColumnType("date")
                        .HasColumnName("settled_on");

                    b.Property<Guid>("ToMember")
                        .HasColumnType("uuid")
                        .HasColumnName("to_member");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_settlements");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_settlements_created_by");

                    b.HasIndex("Currency")
                        .HasDatabaseName("ix_settlements_currency");

                    b.HasIndex("FromMember")
                        .HasDatabaseName("ix_settlements_from_member");

                    b.HasIndex("ToMember")
                        .HasDatabaseName("ix_settlements_to_member");

                    b.HasIndex("GroupId", "ClientId")
                        .IsUnique()
                        .HasDatabaseName("uq_settlements_group_client");

                    b.HasIndex("GroupId", "SettledOn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_settlements_group")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("settlements", null, t =>
                        {
                            t.HasCheckConstraint("ck_settlements_amount_positive", "amount_minor > 0");

                            t.HasCheckConstraint("ck_settlements_distinct_members", "from_member <> to_member");

                            t.HasCheckConstraint("ck_settlements_notes_length", "notes IS NULL OR length(notes) <= 2000");
                        });
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("CZK")
                        .HasColumnName("default_currency")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("DigestOptIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("digest_opt_in");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("cs")
                        .HasColumnName("locale");

                    b.Property<int>("TokenEpoch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("token_epoch");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DefaultCurrency")
                        .HasDatabaseName("ix_users_default_currency");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("email IS NOT NULL AND deleted_at IS NULL");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ActivityLogEntry", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUser")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_activity_log_users_actor_user");

                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_log_groups_group_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.AuthIdentity", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_identities_users_user_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Category", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_categories_groups_group_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ChangeLogEntry", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_change_log_groups_group_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Comment", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_author_user");

                    b.HasOne("Paybitch.Infrastructure.Entities.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_expenses_expense_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_groups_group_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Device", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_users_user_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.EmailLoginToken", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_email_login_tokens_users_user_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Expense", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_categories_category_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_users_created_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_currencies_currency");

                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_group_members_paid_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.RecurringRule", null)
                        .WithMany()
                        .HasForeignKey("RecurringRuleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_expenses_recurring_rules_recurring_rule_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ExpenseSplit", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_splits_expenses_expense_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_splits_group_members_group_member_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.ExportResult", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_export_results_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_export_results_users_requested_by");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Group", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_groups_users_created_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("DefaultCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_groups_currencies_default_currency");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.GroupMember", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FormerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_members_users_former_user_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_members_users_user_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Invite", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invites_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invites_users_invited_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invites_group_members_member_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.NotificationPref", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notification_prefs_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_prefs_users_user_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RecurringRule", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_rules_categories_category_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_rules_users_created_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_rules_currencies_currency");

                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_rules_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("PaidBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_rules_group_members_paid_by");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RecurringRuleSplit", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_rule_splits_group_members_group_member_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.RecurringRule", null)
                        .WithMany()
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_rule_splits_recurring_rules_rule_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.RefreshToken", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.Settlement", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_settlements_users_created_by");

                    b.HasOne("Paybitch.Infrastructure.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("Currency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_currencies_currency");

                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("FromMember")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_group_members_from_member");

                    b.HasOne("Paybitch.Infrastructure.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_groups_group_id");

                    b.HasOne("Paybitch.Infrastructure.Entities.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("ToMember")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlements_group_members_to_member");
                });

            modelBuilder.Entity("Paybitch.Infrastructure.Entities.User", b =>
                {
                    b.HasOne("Paybitch.Infrastructure.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("DefaultCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_currencies_default_currency");
                });
#pragma warning restore 612, 618
        }
    }
}
